swagger: '2.0'
# paths
paths:
  login:
    post:
      summary: 'User authentication'
      tags:
        - 'auth'
      parameters:
      - name: body
        in: body
        schema:
          required:
            - data
          properties:
            data: 
              type: object
              required:
                - type
                - attributes
              properties:
                type:
                  type: string
                  enum: 
                    - userInput
                attributes:
                  type: object
                  required:
                    - email
                    - password
                  properties:
                    email: 
                      type: string
                      example:
                        john@domain.com
                    password:
                      type: string
                      example:
                        123456
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - meta
              - data
            properties:
              meta:
                type: object
                required:
                  - access_token
                  - token_type
                  - expires_in
                properties:
                  access_token:
                    type: string
                    example: a4f2b8c2e6adc3ccfc99f3694f6f16d17776312d
                  token_type:
                    type: string
                    default: Bearer
                  expires_in:
                    type: integer
                    minimum: 60
                    example: 3600
              data:
                $ref: '../models.yaml#/definitions/UserResource'
        422:
          $ref: '../responses.yaml#/responses/422'
  verify:
    post:
      summary: 'User token verification'
      tags:
        - 'auth'
      parameters:
      - name: body
        in: body
        schema:
          required:
            - meta
          properties:
            meta: 
              type: object
              required:
                - access_token
              properties:
                access_token:
                  type: string
                  example: 
                    - a4f2b8c2e6adc3ccfc99f3694f6f16d17776312d
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - data
            properties:
              data: 
                $ref: '#/definitions/UserResource'
        404:
          $ref: '../responses.yaml#/responses/404'

  resetPassword:
    post:
      summary: 'Request password reset email.'
      tags:
        - 'auth'
      parameters:
      - name: body
        in: body
        schema:
          required:
            - data
          properties:
            data: 
              type: object
              required:
                - type
                - attributes
              properties:
                type:
                  type: string
                  enum: 
                    - userInput
                attributes:
                  type: object
                  required:
                    - email
                  properties:
                    email: 
                      type: string
                      example:
                        john@domain.com
      responses:
        204:
          description: Password reset link has been sent to user's email.
        422:
          $ref: '../responses.yaml#/responses/422'

  verifyResetToken:
    post:
      summary: 'Verify password reset token.'
      tags:
        - 'auth'
      parameters:
      - name: body
        in: body
        schema:
          required:
            - data
          properties:
            data: 
              type: object
              required:
                - type
                - attributes
              properties:
                type:
                  type: string
                  enum: 
                    - userInput
                attributes:
                  type: object
                  required:
                    - reset_token
                  properties:
                    reset_token: 
                      type: string
                      example:
                        6adc3ccfc99f3694f6f16d17776312d
      responses:
        204:
          description: Reset token is valid.
        404:
          $ref: '../responses.yaml#/responses/404'

  emailConfirm:
    post:
      summary: 'Confirm user email address w/ token from verification email.'
      tags:
        - 'auth'
      parameters:
        - name: resetToken
          in: query
          type: string
          required: true
      responses:
        204:
          description: Reset token is valid.
        404:
          $ref: '../responses.yaml#/responses/404'

  updatePassword:
    post:
      summary: 'Update user password'
      tags:
        - 'auth'
      parameters:
      - name: body
        in: body
        schema:
          required:
            - data
          properties:
            data: 
              type: object
              required:
                - type
                - attributes
              properties:
                type:
                  type: string
                  enum: 
                    - userInput
                attributes:
                  type: object
                  required:
                    - reset_token
                    - password
                  properties:
                    reset_token: 
                      type: string
                      example:
                        6adc3ccfc99f3694f6f16d17776312d
                    password:
                      type: string 
      responses:
        204:
          $ref: '../responses.yaml#/responses/204'
        404:
          $ref: '../responses.yaml#/responses/404'
          
          
